<a href="https://colab.research.google.com/github/codeehere/DeepLearning/blob/main/TesorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DeepLearning with TensorFlow

**Tensor:** It is just a general name for data stored in multiple dimensions



**Neuron:** Is the smallest unit of Neural Network that obay a basic equation **" Activation( w1x1 + w2x2 + w3x3 - b )  "**

In [29]:
import tensorflow as tf
import torch as th

Dim1_const_data = tf.constant([1,2,3,4])
print(Dim1_const_data.ndim)


Dim2_const_data = tf.constant([
    [1,2,3],
    [3,2,1],
    [4,5,6]
])
print(Dim2_const_data.ndim)


Dim3_const_data = tf.constant([
    [[1,2,3]],
     [[3,2,1]],
      [[4,5,6]]
])
print(Dim3_const_data.ndim)

1
2
3


In [30]:
# TensorFlow veriable

Dim1_var_data = tf.Variable([1,2,3,4])
Dim1_var_data.shape

# Assign at TensorFlow

Constant_data = tf.constant([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])
Variable_data = tf.Variable([
    [1,2,3],
    [1,2,3],
    [1,2,3]
],dtype=tf.float16)

print(Constant_data)
print(Variable_data)

# Assign a value in a Variable Tensor
Variable_data[2,1].assign(10)
Variable_data


# Assign a value forcefully at a constant Tensor is not possibel
# Constant_data[0,0].assign(10) - Throw an Error ( 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign' )



tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float16, numpy=
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float16)>


<tf.Variable 'Variable:0' shape=(3, 3) dtype=float16, numpy=
array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1., 10.,  3.]], dtype=float16)>

### Getting Information from Tensor

 * **Shape:** The length (number of elements) of each of the dimensions of a
tensor.
* **Rank:** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* **Axis or Dimension:** A particular dimension of a tensor.
* **Size:** The total number of items in the tensor.

In [31]:
# Creating a Rank 4 Tensor

Rank_4_Tensor = tf.zeros([2,3,4,5])
Rank_4_Tensoe

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [32]:
# See details

print("Datatypre of all Tensors: ",tf.dtypes.as_dtype(Rank_4_Tensor.dtype))
print("Shape of all Tensors: ",Rank_4_Tensor.shape)
print("Rank of all Tensors: ",Rank_4_Tensor.ndim)
print("Elements along axis 0 of Tensors: ",Rank_4_Tensor.shape[0])
print("Elements along last axis of Tensors: ",Rank_4_Tensor.shape[-1])
print("Total elements in Tensors: ",tf.size(Rank_4_Tensor).numpy())

Datatypre of all Tensors:  <dtype: 'float32'>
Shape of all Tensors:  (2, 3, 4, 5)
Rank of all Tensors:  4
Elements along axis 0 of Tensors:  2
Elements along last axis of Tensors:  5
Total elements in Tensors:  120


### Indexing & Expanding Tensors

We can also index tensors just like python list

In [33]:
# Get the first 2 items of each dimension
Rank_4_Tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
# Get the dimension from each index except for the final one
Rank_4_Tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>